### PR TITLE
Update framework to support latest swift version 5.4

### PR DESCRIPTION
**Pull request by aarjan**
Tested on both Simulator and Physical device with Xcode version 12.5 and Swift version 5.4

### CODE REVIEW

**Comment by awazgyawali** [comment]
@ayyshim Any plans on merging this?

**Comment by ayyshim** [comment]
Merged and published!

**Comment by ayyshim** [comment]
@all-contributors please add @aarjan for code

**Comment by ayyshim** [comment]
@all-contributors please add @aarjan for code

**Comment by ayyshim** [comment]
@all-contributors please add @aarjan for code

**Pull request merged**
